version: '3.4'

services:
  MesosApi:
    image: MesosApi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
    depends_on: 
      - migrations
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password_01"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    depends_on: 
      - migrations
  migrations:
    build: 
      context: .
      dockerfile: Migrations.Dockerfile